export const GOODS = {
    "": 0,
    "Acid": 0,
    "Acron Drug": 0,
    "Adhesive": 0,
    "Aluminum": 0,
    "Ammunition": 0,
    "Ammunition L": 0,
    "Ammunition M": 0,
    "Ammunition S": 0,
    "Antigrav Generator": 0,
    "Antigrav Unit": 0,
    "Beer": 0,
    "Bio Gas": 0,
    "Body Armor": 0,
    "Book": 0,
    "Carbon": 0,
    "Cattle": 0,
    "Chemicals": 0,
    "Chlorine": 0,
    "Clothes": 0,
    "Coal": 0,
    "Cocoa": 0,
    "Coffee": 0,
    "Computation Mainframe": 0,
    "Conductor": 0,
    "Coolant": 0,
    "Copper": 0,
    "Corn": 0,
    "Crystal": 0,
    "Dairy": 0,
    "Diamond": 0,
    "Display": 0,
    "Drill": 0,
    "Drone": 0,
    "Electro Magnet": 0,
    "Electromagnetic Charge": 0,
    "Electron Accelerator": 0,
    "Energy Cell": 0,
    "Energy Container": 0,
    "Energy Generator": 0,
    "Energy Inverter": 0,
    "Energy Tube": 0,
    "Explosive Charge": 0,
    "Fabric": 0,
    "Fertilizer": 0,
    "Fish": 0,
    "Fluorine": 0,
    "Food": 0,
    "Food Bar": 0,
    "Force Generator": 0,
    "Fruit": 0,
    "Fuel": 0,
    "Fungus": 0,
    "Fusion Core": 0,
    "Fusion Generator": 0,
    "Gauss Rail": 0,
    "Gems": 0,
    "Glass": 0,
    "Gold": 0,
    "Gun": 0,
    "Helium": 0,
    "High Capacity Lens": 0,
    "High Pressure Tube": 0,
    "Hydrogen": 0,
    "Industrial Tesla Coil": 0,
    "Jewelry": 0,
    "Laser Compressor": 0,
    "Laser Head": 0,
    "Laser Modulator": 0,
    "Lead": 0,
    "Leather": 0,
    "Liquor": 0,
    "Luxury Food": 0,
    "Meat": 0,
    "Medical Supplies": 0,
    "Metal Plate": 0,
    "Microchip": 0,
    "Military Tesla Coil": 0,
    "Mineral": 0,
    "Mining Robot": 0,
    "Morn Drug": 0,
    "Nanobot": 0,
    "Neon": 0,
    "Neutron Accelerator": 0,
    "Nitrogen": 0,
    "Oil": 0,
    "Ore": 0,
    "Oxygen": 0,
    "Paint": 0,
    "Paper": 0,
    "Plankton": 0,
    "Plant": 0,
    "Plasma Cell": 0,
    "Plastic": 0,
    "Platinum": 0,
    "Potato": 0,
    "Power Unit": 0,
    "Processor": 0,
    "Protein": 0,
    "Proton Accelerator": 0,
    "Raw Oil": 0,
    "Rice": 0,
    "Rocket": 0,
    "Rubber": 0,
    "Satellite": 0,
    "Scrap Metal": 0,
    "Semi Conductor": 0,
    "Servo": 0,
    "Sheep": 0,
    "Silicon": 0,
    "Silver": 0,
    "Slave": 0,
    "Solar Cell": 0,
    "Solar Panel": 0,
    "Solvent": 0,
    "Spices": 0,
    "Steel": 0,
    "Steel Tube": 0,
    "Targeting Card": 0,
    "Targeting System": 0,
    "Tea": 0,
    "Teleporter": 0,
    "Tools": 0,
    "Toxic Waste": 0,
    "Transformator": 0,
    "Turbine": 0,
    "Vegetable": 0,
    "Vehicle": 0,
    "War Robot": 0,
    "Warhead": 0,
    "Water": 0,
    "Wheat": 0,
    "Wine": 0,
    "Wire": 0,
    "Wood": 0,
    "Zinc": 0,
}
