export const INTL: { [key: string]: any } = {
    STATION: {
        "en-US": {
            "Turret Factory Supplier": "Turret Factory Supplier",
            "Turret Factory": "Turret Factory",
            "Aluminum Mine": "Aluminum Mine",
            "Ammunition Factory": "Ammunition Factory",
            "Conductor Factory": "Conductor Factory",
            "Copper Mine": "Copper Mine",
            "Planetary Trading Post": "Planetary Trading Post",
            "Crystal Farm": "Crystal Farm",
            "Electro Magnet Factory": "Electro Magnet Factory",
            "Electromagnetic Charge Factory": "Electromagnetic Charge Factory",
            "Solar Power Plant": "Solar Power Plant",
            "Energy Container Factory": "Energy Container Factory",
            "Energy Inverter Factory": "Energy Inverter Factory",
            "Energy Tube Factory": "Energy Tube Factory",
            "Explosive Charge Factory": "Explosive Charge Factory",
            "Force Generator Factory": "Force Generator Factory",
            "Fuel Factory": "Fuel Factory",
            "Gauss Rail Factory": "Gauss Rail Factory",
            "Noble Metal Mine": "Noble Metal Mine",
            "High Capacity Lens Factory": "High Capacity Lens Factory",
            "High Pressure Tube Factory": "High Pressure Tube Factory",
            "Tesla Coil Factory": "Tesla Coil Factory",
            "Laser Compressor Factory": "Laser Compressor Factory",
            "Laser Head Factory": "Laser Head Factory",
            "Laser Modulator Factory": "Laser Modulator Factory",
            "Lead Mine": "Lead Mine",
            "Nanobot Factory": "Nanobot Factory",
            "Plasma Cell Factory": "Plasma Cell Factory",
            "Power Unit Factory": "Power Unit Factory",
            "Rocket Factory": "Rocket Factory",
            "Servo Factory": "Servo Factory",
            "Steel Factory": "Steel Factory",
            "Steel Tube Factory": "Steel Tube Factory",
            "Computer Component Factory": "Computer Component Factory",
            "Targeting Card Factory": "Targeting Card Factory",
            "Transformator Factory": "Transformator Factory",
            "Warhead Factory": "Warhead Factory",
            "Wire Manufacturer": "Wire Manufacturer",
            "Zinc Mine": "Zinc Mine",
        },
        "ru": {
            "Turret Factory Supplier": "Поставщик фабрики турелей",
            "Turret Factory": "Фабрика турелей",
            "Aluminum Mine": "Алюминий шахта",
            "Ammunition Factory": "Фабрика боеприпасов",
            "Conductor Factory": "Фабрика проводник",
            "Copper Mine": "Медь шахта",
            "Planetary Trading Post": "Планетарная торговая фактория",
            "Crystal Farm": "Ферма кристалл",
            "Electro Magnet Factory": "Фабрика электромагнит",
            "Electromagnetic Charge Factory": "",
            "Solar Power Plant": "Солнечная электростанция",
            "Energy Container Factory": "Фабрика аккумулятор",
            "Energy Inverter Factory": "",
            "Energy Tube Factory": "Фабрика энергетическая труба",
            "Explosive Charge Factory": "",
            "Force Generator Factory": "Фабрика генератор силового поля",
            "Fuel Factory": "Фабрика топливо",
            "Gauss Rail Factory": "Фабрика рельсовая пушка Гаусса",
            "Noble Metal Mine": "Рудник благородного металла",
            "High Capacity Lens Factory": "Фабрика линза для мощного лазера",
            "High Pressure Tube Factory": "Фабрика труба высокого давления",
            "Tesla Coil Factory": "Фабрика трансформаторов Тесла",
            "Laser Compressor Factory": "Фабрика лазерный компрессор",
            "Laser Head Factory": "Фабрика лазерная головка",
            "Laser Modulator Factory": "Фабрика лазерный модулятор",
            "Lead Mine": "Свинец шахта",
            "Nanobot Factory": "Фабрика наноробот",
            "Plasma Cell Factory": "Фабрика плазменный элемент",
            "Power Unit Factory": "Фабрика силовая установка",
            "Rocket Factory": "",
            "Servo Factory": "Фабрика сервомеханизм",
            "Steel Factory": "Фабрика сталь",
            "Steel Tube Factory": "Фабрика стальная труба",
            "Computer Component Factory": "Фабрика компьютерных комплектующих",
            "Targeting Card Factory": "Фабрика карта наведения",
            "Transformator Factory": "Фабрика трансформатор",
            "Warhead Factory": "",
            "Wire Manufacturer": "Производитель провод",
            "Zinc Mine": "Цинк шихта",
        }
    },
    TURRET: {
        "en-US": {
            "Chaingun": "Chaingun",
            "Bolter": "Bolter",
            "Laser": "Laser",
            "Plasma Gun": "Plasma Gun",
            "Cannon": "Cannon",
            "Rocket Launcher": "Rocket Launcher",
            "Railgun": "Railgun",
            "Repair Laser": "Repair Laser",
            "Purifying Mining Laser": "Purifying Mining Laser",
            "R-Mining Laser": "R-Mining Laser",
            "Purifying Salvaging Laser": "Purifying Salvaging Laser",
            "R-Salvaging Laser": "R-Salvaging Laser",
            "Force Turret": "Force Turret",
            "Grabber": "Grabber",
            "Tesla": "Tesla",
            "Lightning": "Lightning",
            "Pulse Cannon": "Pulse Cannon",
            "Point-Defense Cannon": "Point-Defense Cannon",
            "Point-Defense Laser": "Point-Defense Laser",
            "Flak/Anti-Fighter cannon": "Flak/Anti-Fighter cannon",
        },
        "ru": {
            "Chaingun": "Пулемет",
            "Bolter": "Болтер",
            "Laser": "Лазер",
            "Plasma Gun": "Плазма",
            "Cannon": "Орудие",
            "Rocket Launcher": "Пусковая установка",
            "Railgun": "Рельсовая пушка",
            "Repair Laser": "Ремотный лазер",
            "Purifying Mining Laser": "Очищающий буровой лазер",
            "R-Mining Laser": "Грубый буровой лазер",
            "Purifying Salvaging Laser": "Очищающий демонтирующий лазер",
            "R-Salvaging Laser": "Грубый демонтирующий лазер",
            "Force Turret": "Силовая орудие",
            "Grabber": "Хвататель",
            "Tesla": "Тесла",
            "Lightning": "Электроразрядное",
            "Pulse Cannon": "Импульсная пушка",
            "Point-Defense Cannon": "Автоматическая пушка прикрытия",
            "Point-Defense Laser": "Лазер прикрытия",
            "Flak/Anti-Fighter cannon": "Орудие против истребителей",
        }
    },
    COMPONENT: {
        "en-US": {
            "Servo": "Servo",
            "Steel Tube": "Steel Tube",
            "Ammunition S": "Ammunition S",
            "Steel": "Steel",
            "Aluminum": "Aluminum",
            "Lead": "Lead",
            "Industrial Tesla Coil": "Industrial Tesla Coil",
            "Electromagnetic Charge": "Electromagnetic Charge",
            "Energy Inverter": "Energy Inverter",
            "Conductor": "Conductor",
            "Power Unit": "Power Unit",
            "Copper": "Copper",
            "Energy Cell": "Energy Cell",
            "Laser Compressor": "Laser Compressor",
            "Laser Modulator": "Laser Modulator",
            "High Capacity Lens": "High Capacity Lens",
            "Rocket": "Rocket",
            "High Pressure Tube": "High Pressure Tube",
            "Fuel": "Fuel",
            "Targeting Card": "Targeting Card",
            "Wire": "Wire",
            "Nanobot": "Nanobot",
            "Transformator": "Transformator",
            "Gold": "Gold",
            "Electro Magnet": "Electro Magnet",
            "Gauss Rail": "Gauss Rail",
            "Laser Head": "Laser Head",
            "Crystal": "Crystal",
            "Plasma Cell": "Plasma Cell",
            "Energy Tube": "Energy Tube",
            "Energy Container": "Energy Container",
            "Military Tesla Coil": "Military Tesla Coil",
            "Force Generator": "Force Generator",
            "Zinc": "Zinc",
            "Warhead": "Warhead",
            "Explosive Charge": "Explosive Charge",
            "Ammunition M": "Ammunition M",
        },
        "ru": {
            "Servo": "Сервомеханизмы",
            "Steel Tube": "Стальные трубы",
            "Ammunition S": "Боеприпасы S",
            "Steel": "Сталь",
            "Aluminum": "Алюминий",
            "Lead": "Свинец",
            "Industrial Tesla Coil": "Промышленный трансформатор Тесла",
            "Electromagnetic Charge": "Электромагнитный заряд",
            "Energy Inverter": "Инвертор энергии",
            "Conductor": "Проводник",
            "Power Unit": "Силовая установка",
            "Copper": "Медь",
            "Energy Cell": "Энергетический элемент",
            "Laser Compressor": "Лазерный компрессор",
            "Laser Modulator": "Лазерный модулятор",
            "High Capacity Lens": "Линза для мощного лазера",
            "Rocket": "Ракета",
            "High Pressure Tube": "Труба высокого давления",
            "Fuel": "Топливо",
            "Targeting Card": "Карта наведения",
            "Wire": "Провод",
            "Nanobot": "Наноробот",
            "Transformator": "Трансформатор",
            "Gold": "Золото",
            "Electro Magnet": "Электромагнит",
            "Gauss Rail": "Рельсовая пушка Гаусса",
            "Laser Head": "Лазерная головка",
            "Crystal": "Кристалл",
            "Plasma Cell": "Плазменный элемент",
            "Energy Tube": "Энергетическая труба",
            "Energy Container": "Аккумулятор",
            "Military Tesla Coil": "Военный трансформатор Тесла",
            "Force Generator": "Генератор силового поля",
            "Zinc": "Цинк",
            "Warhead": "Боеголовка",
            "Explosive Charge": "Заряд взрывчатого вещества",
            "Ammunition M": "Боеприпасы M",
        }
    },
    UI: {
        "en-US": {
            // Common
            "quantity": "Quantity",
            "component": "Component",
            "components": "Components",
            "estimated-price": "Turret recipe price + Estimated price",
            "estimated-volume": "Estimated volume",
            "estimated-price-info": "Price of all components (based on 0% price)",
            "component-source-info": "Turret Factory and Turret Factory Supplier can contain any of these components",
            "dangerous-cargo": "Dangerous cargo",
            "illegal-cargo": "Illegal cargo",

            // Turret
            "add-turret": "Add turret",
            "remove-turret": "Remove turret",
            "turret-price": "Turret price",
            "remove-turret-confirmation": "Are you certain that you wish to remove the turret from the list?",
            "recipe-for-version": "Recipe for:",

            // Theme
            "theme": "Theme",
            "light-theme": "Light",
            "dark-theme": "Dark",
            "system-theme": "System",

            // Language
            "language": "Language",
            "english-language": "English",
            "russian-language": "Russian",
        },
        "ru": {
            // Common
            "quantity": "Количество",
            "component": "Компонент",
            "components": "Компоненты",
            "estimated-price": "Цена рецепта турели + Ожидаемая цена",
            "estimated-volume": "Ожидаемый объем",
            "estimated-price-info": "Цена за все компоненты на основе базовой цены каждого компонента",
            "component-source-info": "Фабрика турелей и Поставщик фабрики турелей может вмещать любой из компонентов",
            "dangerous-cargo": "Опасный груз",
            "illegal-cargo": "Нелегальный груз",

            // Turret
            "add-turret": "Добавить турель",
            "remove-turret": "Удалить турель",
            "turret-price": "Цена турели",
            "remove-turret-confirmation": "Вы уверены, что хотите удалить турель из списка?",
            "recipe-for-version": "Рецепт для:",

            // Theme
            "theme": "Тема",
            "light-theme": "Светлая",
            "dark-theme": "Темная",
            "system-theme": "Системная",

            // Language
            "language": "Язык",
            "english-language": "Английский",
            "russian-language": "Русский",
        }
    }
}