export const INTL: { [key: string]: any } = {
    TURRET: {
        "en-US": {
            "Chaingun": "Chaingun",
            "Bolter": "Bolter",
            "Laser": "Laser",
            "Plasma": "Plasma",
            "Cannon": "Cannon",
            "Rocket Launcher": "Rocket Launcher",
            "Railgun": "Railgun",
            "Repair Turret": "Repair Turret",
            "Mining Laser": "Mining Laser",
            "R-Mining Laser": "R-Mining Laser",
            "R-Salvaging Laser": "R-Salvaging Laser",
            "Salvaging Laser": "Salvaging Laser",
            "Force Turret": "Force Turret",
            "Tesla": "Tesla",
            "Lightning": "Lightning",
            "Pulse Cannon": "Pulse Cannon",
            "Point-Defense Chaingun": "Point-Defense Chaingun",
            "Point-Defense Laser": "Point-Defense Laser",
            "Flak/Anti-Fighter cannon": "Flak/Anti-Fighter cannon",
        },
        "ru": {
            "Chaingun": "Пулемет",
            "Bolter": "Болтер",
            "Laser": "Лазер",
            "Plasma": "Плазма",
            "Cannon": "Пушка",
            "Rocket Launcher": "Пусковая установка",
            "Railgun": "Рельсовая пушка",
            "Repair Turret": "Ремонтная турель",
            "Mining Laser": "Буровой лазер",
            "R-Mining Laser": "Грубый буровой лазер",
            "R-Salvaging Laser": "Грубый демонтирующий лазер",
            "Salvaging Laser": "Демонтирующий лазер",
            "Force Turret": "Гравитационная турель",
            "Tesla": "Тесла",
            "Lightning": "Электроразрядное",
            "Pulse Cannon": "Импульсная пушка",
            "Point-Defense Chaingun": "Пулеметная точечная оборона",
            "Point-Defense Laser": "Лазерная точечная оборона",
            "Flak/Anti-Fighter cannon": "Зенитное/ПВО орудие",
        }
    },
    COMPONENT: {
        "en-US": {
            "Servo": "Servo",
            "Steel Tube": "Steel Tube",
            "Ammunition S": "Ammunition S",
            "Steel": "Steel",
            "Aluminum": "Aluminum",
            "Lead": "Lead",
            "Industrial Tesla Coil": "Industrial Tesla Coil",
            "Electromagnetic Charge": "Electromagnetic Charge",
            "Energy Inverter": "Energy Inverter",
            "Conductor": "Conductor",
            "Power Unit": "Power Unit",
            "Copper": "Copper",
            "Energy Cell": "Energy Cell",
            "Laser Compressor": "Laser Compressor",
            "Laser Modulator": "Laser Modulator",
            "High Capacity Lens": "High Capacity Lens",
            "Rocket": "Rocket",
            "High Pressure Tube": "High Pressure Tube",
            "Fuel": "Fuel",
            "Targeting Card": "Targeting Card",
            "Wire": "Wire",
            "Nanobot": "Nanobot",
            "Transformator": "Transformator",
            "Gold": "Gold",
            "Electro Magnet": "Electro Magnet",
            "Gauss Rail": "Gauss Rail",
            "Laser Head": "Laser Head",
            "Crystal": "Crystal",
            "Plasma Cell": "Plasma Cell",
            "Energy Tube": "Energy Tube",
            "Energy Container": "Energy Container",
            "Military Tesla Coil": "Military Tesla Coil",
            "Force Generator": "Force Generator",
            "Zinc": "Zinc",
            "Warhead": "Warhead",
            "Explosive Charge": "Explosive Charge",
            "Ammunition M": "Ammunition M",
        },
        "ru": {
            "Servo": "Сервомеханизмы",
            "Steel Tube": "Стальные трубы",
            "Ammunition S": "Боеприпасы S",
            "Steel": "Сталь",
            "Aluminum": "Алюминий",
            "Lead": "Свинец",
            "Industrial Tesla Coil": "Промышленный трансформатор Тесла",
            "Electromagnetic Charge": "Электромагнитный заряд",
            "Energy Inverter": "Инвертор энергии",
            "Conductor": "Проводник",
            "Power Unit": "Силовая установка",
            "Copper": "Медь",
            "Energy Cell": "Энергетический элемент",
            "Laser Compressor": "Лазерный компрессор",
            "Laser Modulator": "Лазерный модулятор",
            "High Capacity Lens": "Линза для мощного лазера",
            "Rocket": "Ракета",
            "High Pressure Tube": "Труба высокого давления",
            "Fuel": "Топливо",
            "Targeting Card": "Карта наведения",
            "Wire": "Провод",
            "Nanobot": "Наноробот",
            "Transformator": "Трансформатор",
            "Gold": "Золото",
            "Electro Magnet": "Электромагнит",
            "Gauss Rail": "Рельсовая пушка Гаусса",
            "Laser Head": "Лазерная головка",
            "Crystal": "Кристалл",
            "Plasma Cell": "Плазменный элемент",
            "Energy Tube": "Энергетическая труба",
            "Energy Container": "Аккумулятор",
            "Military Tesla Coil": "Военный трансформатор Тесла",
            "Force Generator": "Генератор силового поля",
            "Zinc": "Цинк",
            "Warhead": "Боеголовка",
            "Explosive Charge": "Заряд взрывчатого вещества",
            "Ammunition M": "Боеприпасы M",
        }
    },
    UI: {
        "en-US": {
            // Common
            "quantity": "Quantity",
            "component": "Component",

            // Turret
            "add-turret": "Add turret",
            "remove-turret": "Remove turret",
            "remove-turret-confirmation": "Are you certain that you wish to remove the turret from the list?",
            "recipe-for-version": "Recipe for:",

            // Theme
            "theme": "Theme",
            "light-theme": "Light",
            "dark-theme": "Dark",
            "system-theme": "System",

            // Language
            "language": "Language",
            "english-language": "English",
            "russian-language": "Russian",
        },
        "ru": {
            // Common
            "quantity": "Количество",
            "component": "Компонент",

            // Turret
            "add-turret": "Добавить турель",
            "remove-turret": "Удалить турель",
            "remove-turret-confirmation": "Вы уверены, что хотите удалить турель из списка?",
            "recipe-for-version": "Рецепт для:",

            // Theme
            "theme": "Тема",
            "light-theme": "Светлая",
            "dark-theme": "Темная",
            "system-theme": "Системная",

            // Language
            "language": "Язык",
            "english-language": "Английский",
            "russian-language": "Русский",
        }
    }
}