export const INTL: { [key: string]: any } = {
    STATION: {
        "en-US": {
            "Turret Factory Supplier": "Turret Factory Supplier",
            "Turret Factory": "Turret Factory",
            "Aluminum Mine": "Aluminum Mine",
            "Ammunition Factory": "Ammunition Factory",
            "Conductor Factory": "Conductor Factory",
            "Copper Mine": "Copper Mine",
            "Planetary Trading Post": "Planetary Trading Post",
            "Crystal Farm": "Crystal Farm",
            "Electro Magnet Factory": "Electro Magnet Factory",
            "Electromagnetic Charge Factory": "Electromagnetic Charge Factory",
            "Solar Power Plant": "Solar Power Plant",
            "Energy Container Factory": "Energy Container Factory",
            "Energy Inverter Factory": "Energy Inverter Factory",
            "Energy Tube Factory": "Energy Tube Factory",
            "Explosive Charge Factory": "Explosive Charge Factory",
            "Force Generator Factory": "Force Generator Factory",
            "Fuel Factory": "Fuel Factory",
            "Gauss Rail Factory": "Gauss Rail Factory",
            "Noble Metal Mine": "Noble Metal Mine",
            "High Capacity Lens Factory": "High Capacity Lens Factory",
            "High Pressure Tube Factory": "High Pressure Tube Factory",
            "Tesla Coil Factory": "Tesla Coil Factory",
            "Laser Compressor Factory": "Laser Compressor Factory",
            "Laser Head Factory": "Laser Head Factory",
            "Laser Modulator Factory": "Laser Modulator Factory",
            "Lead Mine": "Lead Mine",
            "Nanobot Factory": "Nanobot Factory",
            "Plasma Cell Factory": "Plasma Cell Factory",
            "Power Unit Factory": "Power Unit Factory",
            "Rocket Factory": "Rocket Factory",
            "Servo Factory": "Servo Factory",
            "Steel Factory": "Steel Factory",
            "Steel Tube Factory": "Steel Tube Factory",
            "Computer Component Factory": "Computer Component Factory",
            "Targeting Card Factory": "Targeting Card Factory",
            "Transformator Factory": "Transformator Factory",
            "Warhead Factory": "Warhead Factory",
            "Wire Manufacturer": "Wire Manufacturer",
            "Zinc Mine": "Zinc Mine",
        },
        "ru": {
            "Turret Factory": "Фабрика турелей",
            "Turret Factory Supplier": "Поставщик фабрики турелей",
            "Planetary Trading Post": "Планетарная торговая фактория",
            "Solar Power Plant": "Солнечная электростанция",
            "Wire Manufacturer": "Производитель Провод",
            "Crystal Farm": "Ферма (Кристалл)",
            "Noble Metal Mine": "Рудник благородного металла",
            "Aluminum Mine": "Алюминий шахта",
            "Copper Mine": "Медь шахта",
            "Lead Mine": "Свинец шахта",
            "Zinc Mine": "Цинк шихта",
            "Computer Component Factory": "Фабрика компьютерных комплектующих",
            "Ammunition Factory": "Фабрика боеприпасов",
            "Tesla Coil Factory": "Фабрика трансформаторов Тесла",
            "Conductor Factory": "Фабрика Проводник",
            "Electro Magnet Factory": "Фабрика Электромагнит",
            "Electromagnetic Charge Factory": "Фабрика Электромагнитный заряд",
            "Energy Container Factory": "Фабрика Аккумулятор",
            "Energy Inverter Factory": "Фабрика Инвертор энергии",
            "Energy Tube Factory": "Фабрика Энергетическая труба",
            "Explosive Charge Factory": "Фабрика Заряд взрывчатого вещества",
            "Force Generator Factory": "Фабрика Генератор силового поля",
            "Fuel Factory": "Фабрика Топливо",
            "Gauss Rail Factory": "Фабрика Рельсовая пушка Гаусса",
            "High Capacity Lens Factory": "Фабрика Линза для мощного лазера",
            "High Pressure Tube Factory": "Фабрика Труба высокого давления",
            "Laser Compressor Factory": "Фабрика Лазерный компрессор",
            "Laser Head Factory": "Фабрика Лазерная головка",
            "Laser Modulator Factory": "Фабрика Лазерный модулятор",
            "Nanobot Factory": "Фабрика Наноробот",
            "Plasma Cell Factory": "Фабрика Плазменный элемент",
            "Power Unit Factory": "Фабрика Силовая установка",
            "Rocket Factory": "Фабрика Ракета",
            "Servo Factory": "Фабрика Сервомеханизм",
            "Steel Factory": "Фабрика Сталь",
            "Steel Tube Factory": "Фабрика Стальная труба",
            "Targeting Card Factory": "Фабрика Карта наведения",
            "Transformator Factory": "Фабрика Трансформатор",
            "Warhead Factory": "Фабрика Боеголовка",
        }
    },
    TURRET: {
        "en-US": {
            "Chaingun": "Chaingun",
            "Bolter": "Bolter",
            "Laser": "Laser",
            "Plasma": "Plasma",
            "Cannon": "Cannon",
            "Launcher": "Launcher",
            "Railgun": "Railgun",
            "Repair": "Repair",
            "Mining Laser": "Mining Laser",
            "Raw Mining Laser": "Raw Mining Laser",
            "Salvaging Laser": "Salvaging Laser",
            "Raw Salvaging Laser": "Raw Salvaging Laser",
            "Force Gun": "Force Gun",
            "Tesla Gun": "Tesla Gun",
            "Lightning Gun": "Lightning Gun",
            "Pulse Cannon": "Pulse Cannon",
            "Point Defense Cannon": "Point Defense Cannon",
            "Point Defense Laser": "Point Defense Laser",
            "Anti Fighter": "Anti Fighter",
        },
        "ru": {
            "Chaingun": "Автоматическая пушка",
            "Point Defense Cannon": "Автоматическая пушка прикрытия",
            "Point Defense Laser": "Лазер прикрытия",
            "Laser": "Лазер",
            "Mining Laser": "Рудный лазер",
            "Raw Mining Laser": "Груборудный лазер",
            "Salvaging Laser": "Утилизационный лазер",
            "Raw Salvaging Laser": "Лазер для утилизации неочищенной руды",
            "Plasma": "Плазма",
            "Launcher": "Установка",
            "Cannon": "Орудие",
            "Railgun": "Рельсовая пушка",
            "Repair": "Ремонтировать",
            "Bolter": "Болтер",
            "Lightning Gun": "Молниевая пушка",
            "Tesla Gun": "Пушка Тесла",
            "Force Gun": "Силовая пушка",
            "Pulse Cannon": "Импульсное орудие",
            "Anti Fighter": "Против истребителей",
        }
    },
    COMPONENT: {
        "en-US": {
            "Servo": "Servo",
            "Steel Tube": "Steel Tube",
            "Ammunition S": "Ammunition S",
            "Steel": "Steel",
            "Aluminum": "Aluminum",
            "Lead": "Lead",
            "Industrial Tesla Coil": "Industrial Tesla Coil",
            "Electromagnetic Charge": "Electromagnetic Charge",
            "Energy Inverter": "Energy Inverter",
            "Conductor": "Conductor",
            "Power Unit": "Power Unit",
            "Copper": "Copper",
            "Energy Cell": "Energy Cell",
            "Laser Compressor": "Laser Compressor",
            "Laser Modulator": "Laser Modulator",
            "High Capacity Lens": "High Capacity Lens",
            "Rocket": "Rocket",
            "High Pressure Tube": "High Pressure Tube",
            "Fuel": "Fuel",
            "Targeting Card": "Targeting Card",
            "Wire": "Wire",
            "Nanobot": "Nanobot",
            "Transformator": "Transformator",
            "Gold": "Gold",
            "Electro Magnet": "Electro Magnet",
            "Gauss Rail": "Gauss Rail",
            "Laser Head": "Laser Head",
            "Crystal": "Crystal",
            "Plasma Cell": "Plasma Cell",
            "Energy Tube": "Energy Tube",
            "Energy Container": "Energy Container",
            "Military Tesla Coil": "Military Tesla Coil",
            "Force Generator": "Force Generator",
            "Zinc": "Zinc",
            "Warhead": "Warhead",
            "Explosive Charge": "Explosive Charge",
            "Ammunition M": "Ammunition M",
        },
        "ru": {
            "Servo": "Сервомеханизм",
            "Steel Tube": "Стальная труба",
            "Ammunition S": "Боеприпасы S",
            "Steel": "Сталь",
            "Aluminum": "Алюминий",
            "Lead": "Свинец",
            "Industrial Tesla Coil": "Промышленный трансформатор Тесла",
            "Electromagnetic Charge": "Электромагнитный заряд",
            "Energy Inverter": "Инвертор энергии",
            "Conductor": "Проводник",
            "Power Unit": "Силовая установка",
            "Copper": "Медь",
            "Energy Cell": "Энергетический элемент",
            "Laser Compressor": "Лазерный компрессор",
            "Laser Modulator": "Лазерный модулятор",
            "High Capacity Lens": "Линза для мощного лазера",
            "Rocket": "Ракета",
            "High Pressure Tube": "Труба высокого давления",
            "Fuel": "Топливо",
            "Targeting Card": "Карта наведения",
            "Wire": "Провод",
            "Nanobot": "Наноробот",
            "Transformator": "Трансформатор",
            "Gold": "Золото",
            "Electro Magnet": "Электромагнит",
            "Gauss Rail": "Рельсовая пушка Гаусса",
            "Laser Head": "Лазерная головка",
            "Crystal": "Кристалл",
            "Plasma Cell": "Плазменный элемент",
            "Energy Tube": "Энергетическая труба",
            "Energy Container": "Аккумулятор",
            "Military Tesla Coil": "Военный трансформатор Тесла",
            "Force Generator": "Генератор силового поля",
            "Zinc": "Цинк",
            "Warhead": "Боеголовка",
            "Explosive Charge": "Заряд взрывчатого вещества",
            "Ammunition M": "Боеприпасы M",
        }
    },
    UI: {
        "en-US": {
            // Common
            "quantity": "Quantity",
            "component": "Component",
            "components": "Components",
            "estimated-price": "Turret recipe price + Estimated price",
            "estimated-volume": "Estimated volume",
            "estimated-price-info": "Price of all components (based on min price and max price)",
            "component-source-info": '"Turret Factory", "Turret Factory Supplier" and "Trading Post" can contain any of these components',
            "dangerous-cargo": "Dangerous cargo",
            "illegal-cargo": "Illegal cargo",

            // Turret
            "add-turret": "Add turret",
            "remove-turret": "Remove turret",
            "turret-price": "Turret price",
            "remove-turret-confirmation": "Are you certain that you wish to remove the turret from the list?",
            "recipe-for-version": "Recipe for:",

            // Theme
            "theme": "Theme",
            "light-theme": "Light",
            "dark-theme": "Dark",
            "system-theme": "System",

            // Language
            "language": "Language",
            "english-language": "English",
            "russian-language": "Russian",
        },
        "ru": {
            // Common
            "quantity": "Количество",
            "component": "Компонент",
            "components": "Компоненты",
            "estimated-price": "Цена рецепта турели + Ожидаемая цена",
            "estimated-volume": "Ожидаемый объем",
            "estimated-price-info": "Цена за все компоненты на основе базовой цены каждого компонента и максимально возможной",
            "component-source-info": '"Фабрика турелей", "Поставщик фабрики турелей" и "Торговая фактория" может содержать любой из компонентов',
            "dangerous-cargo": "Опасный груз",
            "illegal-cargo": "Нелегальный груз",

            // Turret
            "add-turret": "Добавить турель",
            "remove-turret": "Удалить турель",
            "turret-price": "Цена турели",
            "remove-turret-confirmation": "Вы уверены, что хотите удалить турель из списка?",
            "recipe-for-version": "Рецепт для:",

            // Theme
            "theme": "Тема",
            "light-theme": "Светлая",
            "dark-theme": "Темная",
            "system-theme": "Системная",

            // Language
            "language": "Язык",
            "english-language": "Английский",
            "russian-language": "Русский",
        }
    }
}