import {ComponentMetaType} from "~types";
import {ComponentType} from "~constants/enums/components";
import {SellerType} from "~constants/enums/sellers";

export const ComponentsMeta: Record<ComponentType, ComponentMetaType> = {
    [ComponentType.Aluminum]: {
        price: 200,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/aluminium.png",
        sellers: [SellerType.AluminumMine],
    },
    [ComponentType.AmmunitionM]: {
        price: 422,
        volume: 1.5,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/ammunition-m.png",
        sellers: [SellerType.AmmunitionFactory],
    },
    [ComponentType.AmmunitionS]: {
        price: 422,
        volume: 0.5,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/ammunition-s.png",
        sellers: [SellerType.AmmunitionFactory],
    },
    [ComponentType.Conductor]: {
        price: 168,
        volume: 0.15,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/conductor.png",
        sellers: [SellerType.ConductorFactory],
    },
    [ComponentType.Copper]: {
        price: 350,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/copper.png",
        sellers: [SellerType.CopperMine, SellerType.PlanetaryTradingPost],
    },
    [ComponentType.Crystal]: {
        price: 190,
        volume: 1.5,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/crystal.png",
        sellers: [SellerType.CrystalFarm],
    },
    [ComponentType.ElectroMagnet]: {
        price: 483,
        volume: 0.75,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/electro-magnet.png",
        sellers: [SellerType.ElectroMagnetFactory],
    },
    [ComponentType.ElectromagneticCharge]: {
        price: 13985,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/electromagnetic-charge.png",
        sellers: [SellerType.ElectromagneticChargeFactory],
    },
    [ComponentType.EnergyCell]: {
        price: 50,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/battery-pack-alt.png",
        sellers: [SellerType.SolarPowerPlant],
    },
    [ComponentType.EnergyContainer]: {
        price: 1087,
        volume: 4.5,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/electric.png",
        sellers: [SellerType.EnergyContainerFactory],
    },
    [ComponentType.EnergyInverter]: {
        price: 1277,
        volume: 3,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/energy-inverter.png",
        sellers: [SellerType.EnergyInverterFactory],
    },
    [ComponentType.EnergyTube]: {
        price: 2895,
        volume: 1.5,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/energy-tube.png",
        sellers: [SellerType.EnergyTubeFactory],
    },
    [ComponentType.ExplosiveCharge]: {
        price: 1423,
        volume: 1.5,
        illegal: false,
        dangerous: true,
        icon: "/img/icon/explosive-charge.png",
        sellers: [SellerType.ExplosiveChargeFactory],
    },
    [ComponentType.ForceGenerator]: {
        price: 49576,
        volume: 4,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/force-generator.png",
        sellers: [SellerType.ForceGeneratorFactory],
    },
    [ComponentType.Fuel]: {
        price: 1232,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/fuel.png",
        sellers: [SellerType.FuelFactory],
    },
    [ComponentType.GaussRail]: {
        price: 7735,
        volume: 2,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/gauss-rail.png",
        sellers: [SellerType.GaussRailFactory],
    },
    [ComponentType.Gold]: {
        price: 600,
        volume: 0.5,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/metal-bar.png",
        sellers: [SellerType.NobleMetalMine, SellerType.PlanetaryTradingPost],
    },
    [ComponentType.HighCapacityLens]: {
        price: 4689,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/high-capacity-lens.png",
        sellers: [SellerType.HighCapacityLensFactory],
    },
    [ComponentType.HighPressureTube]: {
        price: 1650,
        volume: 2,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/high-pressure-tube.png",
        sellers: [SellerType.HighPressureTubeFactory],
    },
    [ComponentType.IndustrialTeslaCoil]: {
        price: 10314,
        volume: 5.5,
        illegal: false,
        dangerous: true,
        icon: "/img/icon/industrial-tesla-coil.png",
        sellers: [SellerType.TeslaCoilFactory],
    },
    [ComponentType.LaserCompressor]: {
        price: 6577,
        volume: 1.5,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/laser-compressor.png",
        sellers: [SellerType.LaserCompressorFactory],
    },
    [ComponentType.LaserHead]: {
        price: 4690,
        volume: 2,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/laser-head.png",
        sellers: [SellerType.LaserHeadFactory],
    },
    [ComponentType.LaserModulator]: {
        price: 16742,
        volume: 3,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/laser-modulator.png",
        sellers: [SellerType.LaserModulatorFactory],
    },
    [ComponentType.Lead]: {
        price: 200,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/lead.png",
        sellers: [SellerType.LeadMine, SellerType.PlanetaryTradingPost],
    },
    [ComponentType.MilitaryTeslaCoil]: {
        price: 10314,
        volume: 4.5,
        illegal: false,
        dangerous: true,
        icon: "/img/icon/industrial-tesla-coil.png",
        sellers: [SellerType.TeslaCoilFactory],
    },
    [ComponentType.Nanobot]: {
        price: 1338,
        volume: 0.5,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/nanobots.png",
        sellers: [SellerType.NanobotFactory],
    },
    [ComponentType.PlasmaCell]: {
        price: 174,
        volume: 0.25,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/plasma-cell.png",
        sellers: [SellerType.PlasmaCellFactory],
    },
    [ComponentType.PowerUnit]: {
        price: 1211,
        volume: 5,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/power-unit.png",
        sellers: [SellerType.PowerUnitFactory],
    },
    [ComponentType.Rocket]: {
        price: 11250,
        volume: 4,
        illegal: false,
        dangerous: true,
        icon: "/img/icon/rocket.png",
        sellers: [SellerType.RocketFactory],
    },
    [ComponentType.Servo]: {
        price: 1387,
        volume: 0.25,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/servo.png",
        sellers: [SellerType.ServoFactory],
    },
    [ComponentType.Steel]: {
        price: 277,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/i-beam.png",
        sellers: [SellerType.SteelFactory],
    },
    [ComponentType.SteelTube]: {
        price: 704,
        volume: 3,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/steel-tube.png",
        sellers: [SellerType.SteelTubeFactory],
    },
    [ComponentType.TargetingCard]: {
        price: 11873,
        volume: 0.5,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/targeting-card.png",
        sellers: [SellerType.ComputerComponentFactory, SellerType.TargetingCardFactory],
    },
    [ComponentType.Transformator]: {
        price: 209,
        volume: 0.2,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/grenade.png",
        sellers: [SellerType.TransformatorFactory],
    },
    [ComponentType.Warhead]: {
        price: 5630,
        volume: 3,
        illegal: false,
        dangerous: true,
        icon: "/img/icon/warhead.png",
        sellers: [SellerType.WarheadFactory],
    },
    [ComponentType.Wire]: {
        price: 95,
        volume: 0.5,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/wire.png",
        sellers: [SellerType.WireManufacturer],
    },
    [ComponentType.Zinc]: {
        price: 250,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/img/icon/zinc.png",
        sellers: [SellerType.ZincMine],
    },
}