import {ComponentMetaType} from "@/types";
import {ComponentType} from "@/constants/enums/components";
import {SellerType} from "@/constants/enums/sellers";

export const ComponentsMeta: Record<ComponentType, ComponentMetaType> = {
    [ComponentType.Aluminum]: {
        price: 200,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/aluminium.png",
        sellers: [SellerType.AluminumMine],
    },
    [ComponentType.AmmunitionM]: {
        price: 422,
        volume: 1.5,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/ammunition-m.png",
        sellers: [SellerType.AmmunitionFactory],
    },
    [ComponentType.AmmunitionS]: {
        price: 422,
        volume: 0.5,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/ammunition-s.png",
        sellers: [SellerType.AmmunitionFactory],
    },
    [ComponentType.Conductor]: {
        price: 168,
        volume: 0.15,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/conductor.png",
        sellers: [SellerType.ConductorFactory],
    },
    [ComponentType.Copper]: {
        price: 350,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/copper.png",
        sellers: [SellerType.CopperMine, SellerType.PlanetaryTradingPost],
    },
    [ComponentType.Crystal]: {
        price: 190,
        volume: 1.5,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/crystal.png",
        sellers: [SellerType.CrystalFarm],
    },
    [ComponentType.ElectroMagnet]: {
        price: 483,
        volume: 0.75,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/electro-magnet.png",
        sellers: [SellerType.ElectroMagnetFactory],
    },
    [ComponentType.ElectromagneticCharge]: {
        price: 13985,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/electromagnetic-charge.png",
        sellers: [SellerType.ElectromagneticChargeFactory],
    },
    [ComponentType.EnergyCell]: {
        price: 50,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/battery-pack-alt.png",
        sellers: [SellerType.SolarPowerPlant],
    },
    [ComponentType.EnergyContainer]: {
        price: 1087,
        volume: 4.5,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/electric.png",
        sellers: [SellerType.EnergyContainerFactory],
    },
    [ComponentType.EnergyInverter]: {
        price: 1277,
        volume: 3,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/energy-inverter.png",
        sellers: [SellerType.EnergyInverterFactory],
    },
    [ComponentType.EnergyTube]: {
        price: 2895,
        volume: 1.5,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/energy-tube.png",
        sellers: [SellerType.EnergyTubeFactory],
    },
    [ComponentType.ExplosiveCharge]: {
        price: 1423,
        volume: 1.5,
        illegal: false,
        dangerous: true,
        icon: "/assets/img/explosive-charge.png",
        sellers: [SellerType.ExplosiveChargeFactory],
    },
    [ComponentType.ForceGenerator]: {
        price: 49576,
        volume: 4,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/force-generator.png",
        sellers: [SellerType.ForceGeneratorFactory],
    },
    [ComponentType.Fuel]: {
        price: 1232,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/fuel.png",
        sellers: [SellerType.FuelFactory],
    },
    [ComponentType.GaussRail]: {
        price: 7735,
        volume: 2,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/gauss-rail.png",
        sellers: [SellerType.GaussRailFactory],
    },
    [ComponentType.Gold]: {
        price: 600,
        volume: 0.5,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/metal-bar.png",
        sellers: [SellerType.NobleMetalMine, SellerType.PlanetaryTradingPost],
    },
    [ComponentType.HighCapacityLens]: {
        price: 4689,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/high-capacity-lens.png",
        sellers: [SellerType.HighCapacityLensFactory],
    },
    [ComponentType.HighPressureTube]: {
        price: 1650,
        volume: 2,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/high-pressure-tube.png",
        sellers: [SellerType.HighPressureTubeFactory],
    },
    [ComponentType.IndustrialTeslaCoil]: {
        price: 10314,
        volume: 5.5,
        illegal: false,
        dangerous: true,
        icon: "/assets/img/industrial-tesla-coil.png",
        sellers: [SellerType.TeslaCoilFactory],
    },
    [ComponentType.LaserCompressor]: {
        price: 6577,
        volume: 1.5,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/laser-compressor.png",
        sellers: [SellerType.LaserCompressorFactory],
    },
    [ComponentType.LaserHead]: {
        price: 4690,
        volume: 2,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/laser-head.png",
        sellers: [SellerType.LaserHeadFactory],
    },
    [ComponentType.LaserModulator]: {
        price: 16742,
        volume: 3,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/laser-modulator.png",
        sellers: [SellerType.LaserModulatorFactory],
    },
    [ComponentType.Lead]: {
        price: 200,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/lead.png",
        sellers: [SellerType.LeadMine, SellerType.PlanetaryTradingPost],
    },
    [ComponentType.MilitaryTeslaCoil]: {
        price: 10314,
        volume: 4.5,
        illegal: false,
        dangerous: true,
        icon: "/assets/img/industrial-tesla-coil.png",
        sellers: [SellerType.TeslaCoilFactory],
    },
    [ComponentType.Nanobot]: {
        price: 1338,
        volume: 0.5,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/nanobots.png",
        sellers: [SellerType.NanobotFactory],
    },
    [ComponentType.PlasmaCell]: {
        price: 174,
        volume: 0.25,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/plasma-cell.png",
        sellers: [SellerType.PlasmaCellFactory],
    },
    [ComponentType.PowerUnit]: {
        price: 1211,
        volume: 5,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/power-unit.png",
        sellers: [SellerType.PowerUnitFactory],
    },
    [ComponentType.Rocket]: {
        price: 11250,
        volume: 4,
        illegal: false,
        dangerous: true,
        icon: "/assets/img/rocket.png",
        sellers: [SellerType.RocketFactory],
    },
    [ComponentType.Servo]: {
        price: 1387,
        volume: 0.25,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/servo.png",
        sellers: [SellerType.ServoFactory],
    },
    [ComponentType.Steel]: {
        price: 277,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/i-beam.png",
        sellers: [SellerType.SteelFactory],
    },
    [ComponentType.SteelTube]: {
        price: 704,
        volume: 3,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/steel-tube.png",
        sellers: [SellerType.SteelTubeFactory],
    },
    [ComponentType.TargetingCard]: {
        price: 11873,
        volume: 0.5,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/targeting-card.png",
        sellers: [SellerType.ComputerComponentFactory, SellerType.TargetingCardFactory],
    },
    [ComponentType.Transformator]: {
        price: 209,
        volume: 0.2,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/grenade.png",
        sellers: [SellerType.TransformatorFactory],
    },
    [ComponentType.Warhead]: {
        price: 5630,
        volume: 3,
        illegal: false,
        dangerous: true,
        icon: "/assets/img/warhead.png",
        sellers: [SellerType.WarheadFactory],
    },
    [ComponentType.Wire]: {
        price: 95,
        volume: 0.5,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/wire.png",
        sellers: [SellerType.WireManufacturer],
    },
    [ComponentType.Zinc]: {
        price: 250,
        volume: 1,
        illegal: false,
        dangerous: false,
        icon: "/assets/img/zinc.png",
        sellers: [SellerType.ZincMine],
    },
}